services:
  app:
    build:
      context: .
      dockerfile: ./skincare-catalog/Dockerfile
    container_name: skincare_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - app_public:/var/www/html/public
    env_file:
      - ./skincare-catalog/.env
    depends_on:
      - db
    networks:
      - app_network
    expose:
      - 9000

  db:
    image: mysql:latest
    container_name: skincare_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    env_file:
      - .env
    volumes:
      - db_api:/var/lib/mysql
    restart: unless-stopped
    networks:
      - app_network

  whatsapp-client:
    build:
      context: .
      dockerfile: ./skincare-whatsapp-client/Dockerfile
    container_name: skincare_whatsapp_client
    restart: unless-stopped
    ports:
      - "5555:5555"
    env_file:
      - ./skincare-whatsapp-client/.env
    volumes:
      - whatsapp-session:/app/.wwebjs_auth
      - whatsapp-cache:/app/.wwebjs_cache
    networks:
      - app_network
    cap_add:
      - SYS_ADMIN
    shm_size: '2gb'

  caddy:
    image: caddy:latest
    container_name: skincare_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - app_public:/var/www/html/public:ro
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./cert:/etc/caddy/certs:ro
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - app_network

volumes:
  app_public:
    driver: local
  db_api:
    driver: local
  whatsapp-session:
    driver: local
  whatsapp-cache:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local

networks:
  app_network:
    driver: bridge