services:

  app:
    build:
      context: .
      dockerfile: ./skincare-catalog/Dockerfile
    container_name: skincare_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./skincare-catalog/storage:/var/www/html/storage
      - ./skincare-catalog/bootstrap/cache:/var/www/html/bootstrap/cache
    env_file:
      - ./skincare-catalog/.env
    depends_on:
      - db
    networks:
      - app_network
    expose:
      - 9000

  db:
    image: mysql:latest
    container_name: skincare_db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "edam15!k2Mp_"
      MYSQL_DATABASE: "newdb"
      MYSQL_USER: "appuser"
      MYSQL_PASSWORD: "edam15!k2Mp_"
    volumes:
      - db_api:/var/lib/mysql
    restart: unless-stopped
    networks:
      - app_network


  whatsapp-client:
    build:
      context: .
      dockerfile: ./skincare-whatsapp-client/Dockerfile
    container_name: skincare_whatsapp_client
    restart: unless-stopped
    ports:
      - "5555:5555"
    env_file:
      - ./skincare-whatsapp-client/.env
    volumes:
      - ./logs:/app/logs
      - whatsapp-session:/app/.wwebjs_auth
      - whatsapp-cache:/app/.wwebjs_cache
    networks:
      - app_network
    cap_add:
      - SYS_ADMIN
    shm_size: '2gb'
  
  vite:
    build:
      context: .
      dockerfile: ./skincare-catalog/vite.dockerfile
    container_name: vite
    ports:
      - "5173:5173"
    volumes:
      - ./skincare-catalog:/app
    stdin_open: true
    tty: true


  caddy:
    image: caddy:latest
    container_name: skincare_caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./skincare-catalog:/var/www/html
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    networks:
      - app_network

volumes:
  db_api:
    driver: local
  whatsapp-session:
    driver: local
  whatsapp-cache:
    driver: local
  caddy_data:
  caddy_config:

networks:
  app_network:
    driver: bridge
